### ISSUE TITLE
内存分配器被写死了

### ISSUE THREAD

**Issue by synodriver** [fumiama/base16384#1]
目前只能是```malloc```， 希望可以改成宏以便使用自定义的allocator

**Comment by synodriver** [comment]
另外，给```LENDAT``` 写个析构函数吧， 比如```void LENDAT_Del(LENDAT** self)```
```
void LENDAT_Del(LENDAT** self)
{
    if(*self!=NULL)
    {
         free((*self)->data);
        (*self)->data = NULL;
        free(*self);
        *self = NULL;
    }
}
```

**Comment by fumiama** [comment]
> 另外，给`LENDAT` 写个析构函数吧， 比如`void LENDAT_Del(LENDAT** self)`
> 
> ```
> void LENDAT_Del(LENDAT** self)
> {
>     if(*self!=NULL)
>     {
>          free((*self)->data);
>         (*self)->data = NULL;
>         free(*self);
>         *self = NULL;
>     }
> }
> ```

这也太cpp了，拿到指针直接free就行。

**Comment by fumiama** [comment]
> 目前只能是`malloc`， 希望可以改成宏以便使用自定义的allocator

我的想法是改成传入buffer+len，自己不分配了。

**Comment by synodriver** [comment]
[能跑了](https://github.com/synodriver/pybase16384)
你的C模块真不错，可惜下一秒就是我的了
