### ISSUE TITLE
[Feature Request]能否发布静态编译的各种架构linux版本运行文件

### ISSUE THREAD

**Issue by egg1234** [fumiama/base16384#17]
例如NAS系统的amd64及armv8，armv7，或梅林固件的armv5，因为这些系统都没有办法具有或安装base16384所需要的依赖库

谢谢！

**Comment by fumiama** [comment]
程序本身其实不需要依赖任何其它依赖库，连libc都不用😂所以你只需要在随便一个对应指令集的设备上编译好程序，拿到哪都能用的。特别是amd64，你看见我 https://github.com/fumiama/base16384/releases/tag/v2.2.3 里面的`base16384.com`文件了吗，这个文件可以在任意amd64指令集的主流系统下运行，包括Windows、Linux和MacOS，你可以试试看。

**Comment by egg1234** [comment]
谢谢指教！之前已经在windows上运行过了，下载尝试的确可以直接在linux上运行，我一直以为windows的com文件和linux的ELF运行格式不能兼容的，现在学到了新知识

有个建议是你应该把这个base16384.com运行文件可以直接在3个操作系统运行的情况写在项目README.md里面，让有兴趣使用这个程序的人都可以马上上手，因为估计很多人都像我一样不知道这个情况，这样也可以加速这个程序的推广使用

再次感谢！

**Comment by fumiama** [comment]
> 你应该把这个base16384.com运行文件可以直接在3个操作系统运行的情况写在项目README.md里面

这个嘛，其实README的第一行就是（

> 这样也可以加速这个程序的推广使用

我采取的方法是将本软件放到各个系统的源中。拿路由器固件举例，现在我已经进入了OpenWrt的packages，任何人都可以轻松地编译使用。如果你用的是Debian/Ubuntu/Deepin这类，那更方便，直接apt install base16384即可。
