### ISSUE TITLE
[Bug Report] 部分文件无法正常编码

### ISSUE THREAD

**Issue by lc6464** [fumiama/base16384#19]
![image](https://github.com/fumiama/base16384/assets/64722907/5b1b9cce-2586-4d5d-8ea5-4bdebfc3fefa)
此文件无法正常编码，程序返回值为 `-1073741819`，stdout 没有输出任何信息，得到的 enc.txt 是空文件（0xFE 0xFF 也没有，完全就是空的，零字节）。
此文件不方便公开发布，如有需要，我可以通过其他非公开渠道发送给您测试。

**Comment by lc6464** [comment]
另外，使用我的 C# 实现编码后，使用此项目 Release 中提供的已编译的文件可以正常解码，且与编码前的文件一致。

**Comment by lc6464** [comment]
这是一些可以公开的数据。
![image](https://github.com/fumiama/base16384/assets/64722907/8dfba50e-4c97-4a05-8ab9-faaf7eaacf4a)
![image](https://github.com/fumiama/base16384/assets/64722907/fcda6bdd-fa08-45b9-a6be-c4834fc53a48)
![image](https://github.com/fumiama/base16384/assets/64722907/8d0369fa-4319-4c2c-b327-20da278ad92f)
![image](https://github.com/fumiama/base16384/assets/64722907/482170b0-1c2c-4f94-8ee3-ce0863b70534)

**Comment by fumiama** [comment]
应该和文件内容无关，只和长度有关。你是使用的最新release吗？

**Comment by fumiama** [comment]
在MacOS下无问题，应该是Windows限定，也许是cosmopolitan适配问题。
<img width="513" alt="截屏2023-08-24 下午4 59 13" src="https://github.com/fumiama/base16384/assets/41315874/3a2ef0b3-206d-4359-80c8-54c0d8640dcf">
<img width="513" alt="截屏2023-08-24 下午5 00 09" src="https://github.com/fumiama/base16384/assets/41315874/78e6e271-fa28-42ee-bad3-3cab0af4c319">

**Comment by lc6464** [comment]
的确是最新的 Release，是否是 Windows 限定我也不太清楚，晚上我换一台 Windows 设备试试，看看是否会在不同版本的 Windows 系统中复现。

**Comment by lc6464** [comment]
的确是文件大小问题，随机生成了同样大小的文件依然失败。
另外实测 Ubuntu 22.04 LTS 下也存在同样问题。
![image](https://github.com/fumiama/base16384/assets/64722907/c64f5dd0-7b05-477c-9efc-5caf3c66e6bc)

**Comment by fumiama** [comment]
刚才发布了v2.2.5，经测试ubuntu下无问题，我去windows下也试了试，似乎也没问题。你再试试。
<img width="516" alt="截屏2023-08-25 下午10 19 36" src="https://github.com/fumiama/base16384/assets/41315874/112c3b57-aab4-4839-9b11-290bb3b97a85">

**Comment by lc6464** [comment]
实测 Windows 11 x64 没问题了，Ubuntu 下暂未测试，晚点或者明天测试下反馈结果。

**Comment by execute233** [comment]
我在两个不同设备上，发现了对于某些大小的文件文件无法正常编码:
windows 11 22H2
![}OLVFD RU 0_@EW9_G1YR@D](https://github.com/fumiama/base16384/assets/69996209/0786828c-08a0-45b5-8db5-23f154fd82f9)
windows server 2012 R2
![C$V(P0DKQ1L)HZ13Z MEQNW](https://github.com/fumiama/base16384/assets/69996209/44fddf05-8a29-46f6-8fb9-a49d5a030246)
我使用了C#版本与其交叉测试，发现应该是您的编码部分有问题。

**Comment by lc6464** [comment]
对于 16977920Bytes 大小的随机文件的复现。
![Screenshot](https://github.com/fumiama/base16384/assets/64722907/c4f39a3f-014c-4d20-ae3b-65f2779781dc)
我使用的随机文件是自行生成的，与 @execute233 使用的并非同一个，因此可以推断是文件大小导致的问题。
需要注意的是，此大小的随机文件通过 .com 版本编码后，解码所得的结果大小与编码前的源文件是不一致的。


另外，您 Release 的 .com 版本无法在 Xiaomi 13（通过 Termux）上运行。
![Screenshot](https://github.com/fumiama/base16384/assets/64722907/ce3eaea0-3b2f-436d-beea-4f0a88f93078)

**Comment by lc6464** [comment]
附上在 Windows 11 x64 平台上已经正常的 2867200Bytes 大小的文件编解码截图。
![image](https://github.com/fumiama/base16384/assets/64722907/71b80a30-6b71-4dd3-9386-0f242205ea37)

**Comment by fumiama** [comment]
> Release 的 .com 版本无法在 Xiaomi 13（通过 Termux）上运行

只能在amd64架构下使用

> 编码部分有问题

我再去看看代码

**Comment by lc6464** [comment]
这是一些随机测试的数据，`Encoded` 代表由 .NET 版本编码而来，`Decoded` 代表由 .NET 版本解码而来，`encodedByC` 代表由您的 v2.2.5 版本 release 编码而来，以此类推。（测试环境为 Ubuntu 20.04.2 LTS）

|文件名|大小|SHA256|
|:---:|:---:|:---:|
|16977920.bin|16977920|15E139FCFCEE924CE48AEB99181B1006E701E1A5FB713BC84D2F6F2AAE87C928|
|16977920.bin.Encoded|19403342|7F7277B78D162BC5A688831ADBF1C40B3508EB2615712DFE1197E969E4FD7C84|
|16977920.bin.Encoded.decodedByC|16977920|15E139FCFCEE924CE48AEB99181B1006E701E1A5FB713BC84D2F6F2AAE87C928|
|16977920.bin.Encoded.Decoded|16977920|15E139FCFCEE924CE48AEB99181B1006E701E1A5FB713BC84D2F6F2AAE87C928|
|16977920.bin.encodedByC|19403354|15EB5368CD38C5E2C27B347A8C97640EF32E5EACA115E738E4C3EE7FF908E5F1|
|16977920.bin.encodedByC.decodedByC|16977930|D5BF99EFAB542FD77716CE88B3057C705A43F99DC469A8C5347707FE8F1491EB|
|16977920.bin.encodedByC.Decoded|16977930|D5BF99EFAB542FD77716CE88B3057C705A43F99DC469A8C5347707FE8F1491EB|
|2867200.bin|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|2867200.bin.Encoded|3276802|A98AFE28C675450635DF9F5BE349ACECEFCB75FC691C1639983BDC1069D53EDC|
|2867200.bin.Encoded.decodedByC|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|2867200.bin.Encoded.Decoded|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|2867200.bin.encodedByC|3276802|A98AFE28C675450635DF9F5BE349ACECEFCB75FC691C1639983BDC1069D53EDC|
|2867200.bin.encodedByC.decodedByC|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|2867200.bin.encodedByC.Decoded|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|3.CR3|31658817|9FF5EB5827C74B960C21E6C226FEF1C12AED90C0DE70DB2675E6AABDDA243500|
|3.CR3.Encoded|36181510|059AD3FA95343506AEF18A295D2BFBF3AEBEA25D05067B057488CC2D7479D256|
|3.CR3.Encoded.decodedByC|31658817|9FF5EB5827C74B960C21E6C226FEF1C12AED90C0DE70DB2675E6AABDDA243500|
|3.CR3.Encoded.Decoded|31658817|9FF5EB5827C74B960C21E6C226FEF1C12AED90C0DE70DB2675E6AABDDA243500|
|3.CR3.encodedByC|36181530|BFCAA6456BACFE9415B5DDBB13A8D0828D2C5F9AD7BDA91E1E68394062020D8B|
|3.CR3.encodedByC.decodedByC|31658831|45CFDB5C28BA0C105B7D6CD2E0B7D360D342C308B35D510FB8CCE1D61F46865F|
|3.CR3.encodedByC.Decoded|31658831|45CFDB5C28BA0C105B7D6CD2E0B7D360D342C308B35D510FB8CCE1D61F46865F|

**Comment by fumiama** [comment]
是之前修windows这个bug修出新bug了，我现在已经重新发布了v2.2.5，你可以再测试一下。

**Comment by lc6464** [comment]
新的 v2.2.5 在 Windows 11 x64 上跑不动。
![image](https://github.com/fumiama/base16384/assets/64722907/d0e62a4e-dbc9-467a-b6da-40ad839ff4d5)
![image](https://github.com/fumiama/base16384/assets/64722907/b3717f2e-b559-47a7-b4aa-911abc2196b4)

**Comment by lc6464** [comment]
Ubuntu 测试：

**Comment by lc6464** [comment]
Ubuntu 测试，似乎没问题了，但是不知为啥在 Windows 下跑不动。
会不会是因为我把 Linux 上下载的直接 Copy 到 Windows 下运行导致的问题？
|文件名|大小|SHA256|
|:---:|:---:|:---:|
|16977920.bin|16977920|15E139FCFCEE924CE48AEB99181B1006E701E1A5FB713BC84D2F6F2AAE87C928|
|16977920.bin.Encoded|19403342|7F7277B78D162BC5A688831ADBF1C40B3508EB2615712DFE1197E969E4FD7C84|
|16977920.bin.Encoded.Decoded|16977920|15E139FCFCEE924CE48AEB99181B1006E701E1A5FB713BC84D2F6F2AAE87C928|
|16977920.bin.Encoded.decodedByC|16977920|15E139FCFCEE924CE48AEB99181B1006E701E1A5FB713BC84D2F6F2AAE87C928|
|16977920.bin.encodedByC|19403342|7F7277B78D162BC5A688831ADBF1C40B3508EB2615712DFE1197E969E4FD7C84|
|16977920.bin.encodedByC.Decoded|16977920|15E139FCFCEE924CE48AEB99181B1006E701E1A5FB713BC84D2F6F2AAE87C928|
|16977920.bin.encodedByC.decodedByC|16977920|15E139FCFCEE924CE48AEB99181B1006E701E1A5FB713BC84D2F6F2AAE87C928|
|2867200.bin|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|2867200.bin.Encoded|3276802|A98AFE28C675450635DF9F5BE349ACECEFCB75FC691C1639983BDC1069D53EDC|
|2867200.bin.Encoded.Decoded|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|2867200.bin.Encoded.decodedByC|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|2867200.bin.encodedByC|3276802|A98AFE28C675450635DF9F5BE349ACECEFCB75FC691C1639983BDC1069D53EDC|
|2867200.bin.encodedByC.Decoded|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|2867200.bin.encodedByC.decodedByC|2867200|25576F4568C77477B96A04E18A29F5DA903601AB51A2E9CCFE16D2120DFF4EB3|
|3.CR3|31658817|9FF5EB5827C74B960C21E6C226FEF1C12AED90C0DE70DB2675E6AABDDA243500|
|3.CR3.Encoded|36181510|059AD3FA95343506AEF18A295D2BFBF3AEBEA25D05067B057488CC2D7479D256|
|3.CR3.Encoded.Decoded|31658817|9FF5EB5827C74B960C21E6C226FEF1C12AED90C0DE70DB2675E6AABDDA243500|
|3.CR3.Encoded.decodedByC|31658817|9FF5EB5827C74B960C21E6C226FEF1C12AED90C0DE70DB2675E6AABDDA243500|
|3.CR3.encodedByC|36181510|059AD3FA95343506AEF18A295D2BFBF3AEBEA25D05067B057488CC2D7479D256|
|3.CR3.encodedByC.Decoded|31658817|9FF5EB5827C74B960C21E6C226FEF1C12AED90C0DE70DB2675E6AABDDA243500|
|3.CR3.encodedByC.decodedByC|31658817|9FF5EB5827C74B960C21E6C226FEF1C12AED90C0DE70DB2675E6AABDDA243500|

**Comment by lc6464** [comment]
果然，Linux 下跑过的 COM 文件不能扔到 Windows 下直接跑，得重新下载。
Windows 上也跑通了，目前暂未发现更多编码问题，但新的 v2.2.5 Defender 报毒（v2.2.4 和昨天的 v2.2.5 不会）。

**Comment by execute233** [comment]
详细信息：
![image](https://github.com/fumiama/base16384/assets/69996209/da6dac1c-01e6-499c-b7ef-d22893d241e4)

**Comment by fumiama** [comment]
> 果然，Linux 下跑过的 COM 文件不能扔到 Windows 下直接跑，得重新下载。

是的，这是cosmopolitan原理所致。

> 但新的 v2.2.5 Defender 报毒（v2.2.4 和昨天的 v2.2.5 不会）

这个我无法控制，因为wd对未签名的程序会很严格，它扫描时的算法也没人清楚。当前版本和之前的代码差距不大，怀疑是wd更新了病毒库，你现在把老版本下载下来看看，估计也一样报毒。

**Comment by execute233** [comment]
貌似只有您的2.5.5和2.1.1版本会报毒：
![W12$2}6N36QE(JHO}H(17J4](https://github.com/fumiama/base16384/assets/69996209/19a20af8-c219-4bc1-b2c2-b8f8fa3be8c2)
已使用目前最新的病毒库。

**Comment by fumiama** [comment]
那就不得而知了，代码变得也不多，只能归因于wd的神秘检测算法了。

**Comment by lc6464** [comment]
扔给 MS 检测一下🤔
@execute233

**Comment by lc6464** [comment]
看起来应该没啥问题了，议题先关了。
